import "./globals.css";
import { Sidebar, TopBar } from "./ui";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bgColor = "bg-black";
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <Sidebar/>
        <main className={`flex flex-col w-full ${bgColor}`}>
          <TopBar/>
          <div className="w-full p-6 bg-neutral-900 h-screen rounded-tl-2xl">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}


