"use client"
import Head from "next/head";
import "./globals.css";
import { Sidebar, TopBar } from "./ui";
import { Geist, Geist_Mono } from "next/font/google";
import { useState } from "react";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Sidebar isSidebarOpen={sidebarOpen} toggleSideBar={setSidebarOpen} />
        <main className={`flex flex-col w-full bg-black`}>
          <TopBar toggleSideBar={() => setSidebarOpen(!sidebarOpen)} />
          <div className="absolute top-16 sm:left-24 w-screen sm:w-[calc(100%-6rem)] h-[calc(100%-4rem)] p-6 bg-neutral-900 rounded-t-2xl overflow-y-auto no-scrollbar">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}


